server:
  port: 9002
spring:
  #给项目来个名字
  application:
    name: rabbitmq-consumer
  #配置rabbitMq 服务器
  rabbitmq:
    host: localhost
    port: 5672
#    username: skywalker
#    password: skywalker
#    #虚拟host 可以不设置,使用server默认host
#    virtual-host: skywalker-virtualhost
